<?php

namespace SEOPressPro\Helpers\Settings;

defined('ABSPATH') or exit('Cheatin&#8217; uh?');

abstract class LocalBusinessHelper {
    public static function getListTypes() {
        $types = [
            ['value' => 'LocalBusiness', 'label' => __('Local Business (default)', 'webseo')],
            ['value' => 'AnimalShelter', 'label' => __('Animal Shelter', 'webseo')],
            ['value' => 'AutomotiveBusiness', 'label' => __('Automotive Business', 'webseo')],
            ['value' => 'AutoBodyShop', 'label' => __('|-Auto Body Shop', 'webseo')],
            ['value' => 'AutoDealer', 'label' => __('|-Auto Dealer', 'webseo')],
            ['value' => 'AutoPartsStore', 'label' => __('|-Auto Parts Store', 'webseo')],
            ['value' => 'AutoRental', 'label' => __('|-Auto Rental', 'webseo')],
            ['value' => 'AutoRepair', 'label' => __('|-Auto Repair', 'webseo')],
            ['value' => 'Auto Wash', 'label' => __('|-AutoWash', 'webseo')],
            ['value' => 'GasStation', 'label' => __('|-Gas Station', 'webseo')],
            ['value' => 'MotorcycleDealer', 'label' => __('|-Motorcycle Dealer', 'webseo')],
            ['value' => 'MotorcycleRepair', 'label' => __('|-Motorcycle Repair', 'webseo')],
            ['value' => 'ChildCare', 'label' => __('Child Care', 'webseo')],
            ['value' => 'DryCleaningOrLaundry', 'label' => __('Dry Cleaning Or Laundry', 'webseo')],
            ['value' => 'EmergencyService', 'label' => __('Emergency Service', 'webseo')],
            ['value' => 'FireStation', 'label' => __('|-Fire Station', 'webseo')],
            ['value' => 'Hospital', 'label' => __('|-Hospital', 'webseo')],
            ['value' => 'PoliceStation', 'label' => __('|-Police Station', 'webseo')],
            ['value' => 'EmploymentAgency', 'label' => __('Employment Agency', 'webseo')],
            ['value' => 'EntertainmentBusiness', 'label' => __('Entertainment Business', 'webseo')],
            ['value' => 'AdultEntertainment', 'label' => __('|-Adult Entertainment', 'webseo')],
            ['value' => 'AmusementPark', 'label' => __('|-Amusement Park', 'webseo')],
            ['value' => 'ArtGallery', 'label' => __('|-Art Gallery', 'webseo')],
            ['value' => 'Casino', 'label' => __('|-Casino', 'webseo')],
            ['value' => 'ComedyClub', 'label' => __('|-Comedy Club', 'webseo')],
            ['value' => 'MovieTheater', 'label' => __('|-Movie Theater', 'webseo')],
            ['value' => 'NightClub', 'label' => __('|-Night Club', 'webseo')],
            ['value' => 'FinancialService', 'label' => __('Financial Service', 'webseo')],
            ['value' => 'AccountingService', 'label' => __('|-Accounting Service', 'webseo')],
            ['value' => 'AutomatedTeller', 'label' => __('|-Automated Teller', 'webseo')],
            ['value' => 'BankOrCreditUnion', 'label' => __('|-Bank Or Credit Union', 'webseo')],
            ['value' => 'InsuranceAgency', 'label' => __('|-Insurance Agency', 'webseo')],
            ['value' => 'FoodEstablishment', 'label' => __('Food Establishment', 'webseo')],
            ['value' => 'Bakery', 'label' => __('|-Bakery', 'webseo')],
            ['value' => 'BarOrPub', 'label' => __('|-Bar Or Pub', 'webseo')],
            ['value' => 'Brewery', 'label' => __('|-Brewery', 'webseo')],
            ['value' => 'CafeOrCoffeeShop', 'label' => __('|-Cafe Or Coffee Shop', 'webseo')],
            ['value' => 'FastFoodRestaurant', 'label' => __('|-Fast Food Restaurant', 'webseo')],
            ['value' => 'IceCreamShop', 'label' => __('|-Ice Cream Shop', 'webseo')],
            ['value' => 'Restaurant', 'label' => __('|-Restaurant', 'webseo')],
            ['value' => 'Winery', 'label' => __('|-Winery', 'webseo')],
            ['value' => 'GovernmentOffice', 'label' => __('Government Office', 'webseo')],
            ['value' => 'PostOffice', 'label' => __('|-PostOffice', 'webseo')],
            ['value' => 'HealthAndBeautyBusiness', 'label' => __('Health And Beauty Business', 'webseo')],
            ['value' => 'BeautySalon', 'label' => __('|-Beauty Salon', 'webseo')],
            ['value' => 'DaySpa', 'label' => __('|-Day Spa', 'webseo')],
            ['value' => 'HairSalon', 'label' => __('|-Hair Salon', 'webseo')],
            ['value' => 'HealthClub', 'label' => __('|-Health Club', 'webseo')],
            ['value' => 'NailSalon', 'label' => __('|-Nail Salon', 'webseo')],
            ['value' => 'TattooParlor', 'label' => __('|-Tattoo Parlor', 'webseo')],
            ['value' => 'HomeAndConstructionBusiness', 'label' => __('Home And Construction Business', 'webseo')],
            ['value' => 'Electrician', 'label' => __('|-Electrician', 'webseo')],
            ['value' => 'HVACBusiness', 'label' => __('|-HVAC Business', 'webseo')],
            ['value' => 'HousePainter', 'label' => __('|-House Painter', 'webseo')],
            ['value' => 'Locksmith', 'label' => __('|-Locksmith', 'webseo')],
            ['value' => 'MovingCompany', 'label' => __('|-Moving Company', 'webseo')],
            ['value' => 'Plumber', 'label' => __('|-Plumber', 'webseo')],
            ['value' => 'RoofingContractor', 'label' => __('|-Roofing Contractor', 'webseo')],
            ['value' => 'InternetCafe', 'label' => __('Internet Cafe', 'webseo')],
            ['value' => 'MedicalBusiness', 'label' => __('Medical Business', 'webseo')],
            ['value' => 'CommunityHealth', 'label' => __('|-Community Health', 'webseo')],
            ['value' => 'Dentist', 'label' => __('|-Dentist', 'webseo')],
            ['value' => 'Dermatology', 'label' => __('|-Dermatology', 'webseo')],
            ['value' => 'DietNutrition', 'label' => __('|-Diet Nutrition', 'webseo')],
            ['value' => 'Emergency', 'label' => __('|-Emergency', 'webseo')],
            ['value' => 'Gynecologic', 'label' => __('|-Gynecologic', 'webseo')],
            ['value' => 'MedicalClinic', 'label' => __('|-Medical Clinic', 'webseo')],
            ['value' => 'Midwifery', 'label' => __('|-Midwifery', 'webseo')],
            ['value' => 'Nursing', 'label' => __('|-Nursing', 'webseo')],
            ['value' => 'Obstetric', 'label' => __('|-Obstetric', 'webseo')],
            ['value' => 'Oncologic', 'label' => __('|-Oncologic', 'webseo')],
            ['value' => 'Optician', 'label' => __('|-Optician', 'webseo')],
            ['value' => 'Optometric', 'label' => __('|-Optometric', 'webseo')],
            ['value' => 'Otolaryngologic', 'label' => __('|-Otolaryngologic', 'webseo')],
            ['value' => 'Pediatric', 'label' => __('|-Pediatric', 'webseo')],
            ['value' => 'Pharmacy', 'label' => __('|-Pharmacy', 'webseo')],
            ['value' => 'Physician', 'label' => __('|-Physician', 'webseo')],
            ['value' => 'Physiotherapy', 'label' => __('|-Physiotherapy', 'webseo')],
            ['value' => 'PlasticSurgery', 'label' => __('|-Plastic Surgery', 'webseo')],
            ['value' => 'Podiatric', 'label' => __('|-Podiatric', 'webseo')],
            ['value' => 'PrimaryCare', 'label' => __('|-Primary Care', 'webseo')],
            ['value' => 'Psychiatric', 'label' => __('|-Psychiatric', 'webseo')],
            ['value' => 'PublicHealth', 'label' => __('|-Public Health', 'webseo')],
            ['value' => 'VeterinaryCare', 'label' => __('|-Veterinary Care', 'webseo')],
            ['value' => 'LegalService', 'label' => __('Legal Service', 'webseo')],
            ['value' => 'Attorney', 'label' => __('|-Attorney', 'webseo')],
            ['value' => 'Notary', 'label' => __('|-Notary', 'webseo')],
            ['value' => 'Library', 'label' => __('Library', 'webseo')],
            ['value' => 'LodgingBusiness', 'label' => __('Lodging Business', 'webseo')],
            ['value' => 'BedAndBreakfast', 'label' => __('|-Bed And Breakfast', 'webseo')],
            ['value' => 'Campground', 'label' => __('|-Campground', 'webseo')],
            ['value' => 'Hostel', 'label' => __('|-Hostel', 'webseo')],
            ['value' => 'Hotel', 'label' => __('|-Hotel', 'webseo')],
            ['value' => 'Motel', 'label' => __('|-Motel', 'webseo')],
            ['value' => 'Resort', 'label' => __('|-Resort', 'webseo')],
            ['value' => 'ProfessionalService', 'label' => __('Professional Service', 'webseo')],
            ['value' => 'RadioStation', 'label' => __('Radio Station', 'webseo')],
            ['value' => 'RealEstateAgent', 'label' => __('Real Estate Agent', 'webseo')],
            ['value' => 'RecyclingCenter', 'label' => __('Recycling Center', 'webseo')],
            ['value' => 'SelfStorage', 'label' => __('Real Self Storage', 'webseo')],
            ['value' => 'ShoppingCenter', 'label' => __('Shopping Center', 'webseo')],
            ['value' => 'SportsActivityLocation', 'label' => __('Sports Activity Location', 'webseo')],
            ['value' => 'BowlingAlley', 'label' => __('|-Bowling Alley', 'webseo')],
            ['value' => 'ExerciseGym', 'label' => __('|-Exercise Gym', 'webseo')],
            ['value' => 'GolfCourse', 'label' => __('|-Golf Course', 'webseo')],
            ['value' => 'HealthClub', 'label' => __('|-Health Club', 'webseo')],
            ['value' => 'PublicSwimmingPool', 'label' => __('|-Public Swimming Pool', 'webseo')],
            ['value' => 'SkiResort', 'label' => __('|-Ski Resort', 'webseo')],
            ['value' => 'SportsClub', 'label' => __('|-Sports Club', 'webseo')],
            ['value' => 'StadiumOrArena', 'label' => __('|-Stadium Or Arena', 'webseo')],
            ['value' => 'TennisComplex', 'label' => __('|-Tennis Complex', 'webseo')],
            ['value' => 'Store', 'label' => __('Store', 'webseo')],
            ['value' => 'AutoPartsStore', 'label' => __('|-Auto Parts Store', 'webseo')],
            ['value' => 'BikeStore', 'label' => __('|-Bike Store', 'webseo')],
            ['value' => 'BookStore', 'label' => __('|-Book Store', 'webseo')],
            ['value' => 'ClothingStore', 'label' => __('|-Clothing Store', 'webseo')],
            ['value' => 'ComputerStore', 'label' => __('|-Computer Store', 'webseo')],
            ['value' => 'ConvenienceStore', 'label' => __('|-Convenience Store', 'webseo')],
            ['value' => 'DepartmentStore', 'label' => __('|-Department Store', 'webseo')],
            ['value' => 'ElectronicsStore', 'label' => __('|-Electronics Store', 'webseo')],
            ['value' => 'Florist', 'label' => __('|-Florist', 'webseo')],
            ['value' => 'FurnitureStore', 'label' => __('|-Furniture Store', 'webseo')],
            ['value' => 'GardenStore', 'label' => __('|-Garden Store', 'webseo')],
            ['value' => 'GroceryStore', 'label' => __('|-Grocery Store', 'webseo')],
            ['value' => 'HardwareStore', 'label' => __('|-Hardware Store', 'webseo')],
            ['value' => 'HobbyShop', 'label' => __('|-Hobby Shop', 'webseo')],
            ['value' => 'HomeGoodsStore', 'label' => __('|-Home Goods Store', 'webseo')],
            ['value' => 'JewelryStore', 'label' => __('|-Jewelry Store', 'webseo')],
            ['value' => 'LiquorStore', 'label' => __('|-Liquor Store', 'webseo')],
            ['value' => 'MensClothingStore', 'label' => __('|-Mens Clothing Store', 'webseo')],
            ['value' => 'MobilePhoneStore', 'label' => __('|-Mobile Phone Store', 'webseo')],
            ['value' => 'MovieRentalStore', 'label' => __('|-Movie Rental Store', 'webseo')],
            ['value' => 'MusicStore', 'label' => __('|-Music Store', 'webseo')],
            ['value' => 'OfficeEquipmentStore', 'label' => __('|-Office Equipment Store', 'webseo')],
            ['value' => 'OutletStore', 'label' => __('|-Outlet Store', 'webseo')],
            ['value' => 'PawnShop', 'label' => __('|-Pawn Shop', 'webseo')],
            ['value' => 'PetStore', 'label' => __('|-Pet Store', 'webseo')],
            ['value' => 'ShoeStore', 'label' => __('|-Shoe Store', 'webseo')],
            ['value' => 'SportingGoodsStore', 'label' => __('|-Sporting Goods Store', 'webseo')],
            ['value' => 'TireShop', 'label' => __('|-Tire Shop', 'webseo')],
            ['value' => 'ToyStore', 'label' => __('|-Toy Store', 'webseo')],
            ['value' => 'WholesaleStore', 'label' => __('|-Wholesale Store', 'webseo')],
            ['value' => 'TelevisionStation', 'label' => __('|-Wholesale Store', 'webseo')],
            ['value' => 'TouristInformationCenter', 'label' => __('Tourist Information Center', 'webseo')],
            ['value' => 'TravelAgency', 'label' => __('Travel Agency', 'webseo')],
        ];

        return apply_filters('seopress_schemas_local_business_types', $types);
    }

    /**
     * @since 4.5.0
     *
     * @param string|stdObject $classCallback
     *
     * @return void
     */
    public static function getSettingsSection($classCallback) {
        $idSection = 'seopress_setting_section_local_business';
        $page = 'seopress-settings-admin-local-business';

        $settings = [
            'section' => [
                'id' => $idSection,
                'title' => '',
                'callback' => [$classCallback, 'renderSection'],
                'page' => $page,
            ],
            'fields' => [
                [
                    'id' => 'seopress_local_business_page',
                    'title' => __('Where to display the schema?', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldPage'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_type',
                    'title' => __('Business type', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldType'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_street_address',
                    'title' => __('Street Address', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldStreetAddress'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_address_locality',
                    'title' => __('City', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldAddressLocality'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_address_region',
                    'title' => __('State', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldAddressRegion'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_postal_code',
                    'title' => __('Postal code', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldPostalCode'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_address_country',
                    'title' => __('Country', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldAddressCountry'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_lat',
                    'title' => __('Latitude', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldLatitude'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_lon',
                    'title' => __('Longitude', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldLongitude'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_place_id',
                    'title' => __('Place ID', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldPlaceId'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_url',
                    'title' => __('URL', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldUrl'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_phone',
                    'title' => __('Telephone', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldPhone'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_price_range',
                    'title' => __('Price range', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldPriceRange'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_cuisine',
                    'title' => __('Cuisine served', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldCuisine'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_menu',
                    'title' => __('URL of the menu', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldMenu'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_accepts_reservations',
                    'title' => __('Accepts Reservations', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldAcceptsReservations'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_opening_hours',
                    'title' => __('Opening hours', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldOpeningHours'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_opening_hours_display_format',
                    'title' => __('Display Format', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldOpeningHoursDisplayFormat'],
                    'page' => $page,
                    'section' => $idSection,
                ],
                [
                    'id' => 'seopress_local_business_opening_hours_separator',
                    'title' => __('Time Separator', 'webseo'),
                    'callback' => [$classCallback, 'renderFieldOpeningHoursSeparator'],
                    'page' => $page,
                    'section' => $idSection,
                ],

            ],
        ];

        return $settings;
    }
}
